ALTER TABLE users ADD COLUMN plan_type VARCHAR(20) NOT NULL DEFAULT 'FREE';
ALTER TABLE users ADD COLUMN trial_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN trial_end_date DATETIME DEFAULT NULL;
