server:
  port: 8084
spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:mysql://localhost:3306/nixtap_analytics_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
logging:
  level:
    com.nixtap.analytics: DEBUG
